# Generated by Django 5.1.1 on 2025-09-28 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_remove_project_user_project_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyPlanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('project_workproduct', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safetyplan_detail', to='core.projectworkproduct')),
            ],
        ),
    ]
