# Generated by Django 5.1.1 on 2025-09-30 06:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_project_user_project_users_and_more'),
        ('safety_plan', '0002_safetyplandetail_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetyplandetail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='safetyplandetail',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='safetyplandetail',
            name='owner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='HistoricalSafetyPlanDetail',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project_workproduct', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.projectworkproduct')),
            ],
            options={
                'verbose_name': 'historical safety plan detail',
                'verbose_name_plural': 'historical safety plan details',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='SafetyPlanLog',
        ),
    ]
