# Generated by Django 5.1.1 on 2025-09-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_workproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workproduct',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='workproduct',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='workproduct',
            name='project',
        ),
        migrations.AddField(
            model_name='workproduct',
            name='is_safety_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workproduct',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
