# Generated by Django 5.1.1 on 2025-09-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_workproduct_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='owner',
            new_name='user',
        ),
    ]
