# Generated by Django 5.1.1 on 2025-09-28 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_owner_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workproduct',
            name='app_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='ProjectWorkProductLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tailored_out', models.BooleanField(default=False)),
                ('tailored_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('tailored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectWorkProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tailored_out', models.BooleanField(default=False)),
                ('tailored_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_workproducts', to='core.project')),
                ('tailored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workproduct')),
            ],
            options={
                'unique_together': {('project', 'workproduct')},
            },
        ),
    ]
