# Generated by Django 5.1.1 on 2025-09-16 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_request_id', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('phase', models.CharField(blank=True, choices=[('Change Request Description Phase', 'Change Request Description Phase'), ('Impact Analysis Phase', 'Impact Analysis Phase'), ('Dependent Work Product Analysis Phase', 'Dependent Work Product Analysis Phase'), ('Verification Phase', 'Verification Phase'), ('Closure', 'Closure')], max_length=50)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('summary_of_change', models.TextField(blank=True)),
                ('responsible_person', models.CharField(blank=True, max_length=255)),
                ('document_subject_to_change', models.CharField(blank=True, max_length=255)),
                ('current_version', models.CharField(blank=True, max_length=255)),
                ('configuration_of_the_document', models.CharField(blank=True, max_length=255)),
                ('type_of_change_request', models.CharField(blank=True, max_length=255)),
                ('change_type', models.CharField(blank=True, choices=[('Temporary', 'Temporary'), ('Permanent', 'Permanent')], max_length=50)),
                ('change_period_from', models.DateField(blank=True, null=True)),
                ('change_period_to', models.DateField(blank=True, null=True)),
                ('change_description', models.TextField(blank=True)),
                ('reason_for_change', models.TextField(blank=True)),
                ('phase_status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=50)),
                ('email_ids', models.TextField(blank=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='ImpactAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('responsible_person', models.CharField(blank=True, max_length=100)),
                ('change_severity', models.CharField(blank=True, choices=[('Major', 'Major'), ('Minor', 'Minor')], max_length=50)),
                ('impact_on_functional_safety', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('justification', models.TextField(blank=True)),
                ('change_request_status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Delayed', 'Delayed')], max_length=100)),
                ('rationale_if_rejected_delay', models.TextField(blank=True)),
                ('phase_status', models.CharField(blank=True, max_length=100)),
                ('email_ids', models.TextField(blank=True)),
                ('change_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crms.changerequest')),
            ],
        ),
    ]
